apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: tomcat7
  name: tomcat7
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tomcat7
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tomcat7
    spec:
      containers:
      - image: 10.64.33.81:5000/tomcat:7-serverjre7-centos7
        imagePullPolicy: IfNotPresent
        name: tomcat7
        resources: {}
        volumeMounts:
        - name: sample
          mountPath: /opt/tomcat/webapps/sample.war
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry81
      restartPolicy: Always
      securityContext: {}
      volumes:
      - name: sample
        hostPath:
          path: /go/src/github.com/stackdocker/tomcat-docker/kubernetes/sample.war
